---
- name: Installing LAMP Architecture 
  hosts: webserver
  become: yes
  tasks: 
    - name: Execution Fail if the distribution is not Ubuntu
      fail:
        msg: The playbook only supports Ubuntu distributions
      when: ansible_facts ['distribution'] != "Ubuntu" and ansible_facts ['distribution'] != "CentOS"
    - name: Install LAMP Packages for Ubuntu
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
      when: "'{{ ansible_distribution}}' == 'Ubuntu'"
    - name: Install LAMP Packages for CentOS
      yum: name={{ item }}  state=latest
      loop: [ 'httpd', 'php', 'php-mysql', 'php-fpm' ]
      when: "'{{ ansible_distribution}}' == 'CentOS'"  
   
      
     

         
   

    
