---
- name: Installing LAMP Architecture 
  hosts: all
  become: yes
  tasks:
    - name: install apache
      package:
        name: "{{apache_package}}"
        update_cache: yes
        state: present
   

    
