---
- name: Installing LAMP Architecture 
  hosts: all
  become: yes
  tasks:
    - name: install apache on Ubuntu
      apt:
        name: "{{apache_package1}}"
        update_cache: yes
        state: present
      when: ansible_facts ['distribution'] == "Ubuntu"  
    - name: install apache on CentOS
      yum:
        name: "{{apache_package2}}"
        state: present
      when: ansible_facts ['distribution'] == "CentOS"  
    - name: install php packages for Ubuntu
      apt:
        update_cache: yes
        name: 
           - php
           - libapache2-mod-php
           - php-mysql
           - php-cli
        state: present 
    - name: install php packages for CentOS
      yum:
        name: "{{php_packages2}}"
        state: present
         
   

    
