---
- name: Installing LAMP Architecture 
  hosts: webserver
  become: yes
  tasks:
    - name: install apache on Ubuntu
      apt:
        name: "{{apache_package1}}"
        update_cache: yes
        state: present
      when: ansible_facts ['distribution'] == "Ubuntu"  
    - name: install apache on CentOS
      yum:
        name: "{{apache_package2}}"
        state: present
      when: ansible_facts ['distribution'] == "CentOS"  
    - name: install php packages for Ubuntu
      package:
        name: "{{item}}"
        state: present
      loop: "{{php_packages1}}"
      when: ansible_facts ['distribution'] == "Ubuntu 
    - name: install php packages for CentOS
      package:
        name: "{{item}}"
        state: present
      loop: "{{php_packages2}}"
      when: ansible_facts ['distribution'] == "CentOS"     
   

    
