---
- name: Installing LAMP Architecture 
  hosts: webserver
  become: yes
  tasks: 
    - name: Execution Fail if the distribution is not Ubuntu
      fail:
        msg: The playbook only supports Ubuntu distributions
      when: ansible_facts ['distribution'] != "Ubuntu" and ansible_facts ['distribution'] != "CentOS"
    - name: Install LAMP Packages for Ubuntu
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{php_packages1}}"
   
      
     

         
   

    
