---
- name: Installing LAMP Architecture 
  hosts: all
  become: yes
  tasks:
    - name: install apache on Ubuntu
      apt:
        name: "{{apache_package1}}"
        update_cache: yes
        state: present
      when: ansible_facts ['distribution'] == "Ubuntu"  
    - name: install apache on CentOS
      yum:
        name: "{{apache_package2}}"
        state: present
      when: ansible_facts ['distribution'] == "CentOS" 
    - name: install python apt
      apt:
        name: python-apt
        state: present  
         
   

    
