---
- name: Installing LAMP Architecture 
  hosts: all
  become: yes
  tasks: 
    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
      when: "'{{ ansible_distribution}}' == 'Ubuntu'"
    - name: Install LAMP Packages
      yum: name={{ item }}  state=latest
      loop: [ 'httpd', 'php', 'php-mysql', 'php-fpm' ]
      when: "'{{ ansible_distribution}}' == 'CentOS'"
     

         
   

    
