---
- name: Install dependencies softwares
  become: yes
  hosts: all
  tasks:
    - name: Install Softwares
      package:
        name: "{{item}}"
        state: present
      loop: "{{install_softwares2}}"