---
- name: Installing tomcat 9
  hosts: all
  become: yes
  tasks:
    - name: Update Ubuntu packages and install open-JDK11
      apt:
        name: "{{java_package}}"
        update_cache: yes
        state: present
    - name: Ensure group tomcat exists
      group:
        name: "{{tomcat_group}}"
        state: present 
    - name: Ensure tomcat home directory exsists
      file:
        path: "{{tomcat_directory}}"
        state: directory        
    - name: Ensure user tomcat exsists
      user:
        name: "{{tomcat_user}}"
        group: "{{tomcat_group}}"
        home: "{{tomcat_directory}}"
        shell: "{{tomcat_shell}}" 
    - name: Download tomcat
      get_url:
        url: "{{tomcat_download_url}}"
        dest: "{{tomcat_download_destination}}"
    - name: extract tomcat packages
      unarchive:
        src: "{{tomcat_download_destination}}"
        dest: "{{tomcat_directory}}"
        remote_src: yes

